// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCAppEntityFramework.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221101095000_ass")]
    partial class ass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("MVCAppEntityFramework.Models.BookModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPages")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BookModel");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Viktor",
                            Category = "Cooking",
                            Description = "This book is about cooking.",
                            ISBN = "978-3-16-148410-0",
                            Price = 299.89999999999998,
                            Publisher = "freePublishNet",
                            Title = "Holk Smash 4",
                            TotalPages = 180
                        },
                        new
                        {
                            Id = 2,
                            Author = "SAS",
                            Category = "Airplanes",
                            Description = "This book is about airplanes",
                            ISBN = "978-3-16-148410-0",
                            Price = 100.0,
                            Publisher = "SAS Publishers",
                            Title = "How to build a sinking boat",
                            TotalPages = 10
                        },
                        new
                        {
                            Id = 3,
                            Author = "Homeless Ben",
                            Category = "Aerodynamics",
                            Description = "How drinking keeps me sane",
                            ISBN = "978-3-16-148410-0",
                            Price = 599.89999999999998,
                            Publisher = "Homeless Ben",
                            Title = "Keep Drinking Alcohol",
                            TotalPages = 200
                        },
                        new
                        {
                            Id = 4,
                            Author = "Richard",
                            Category = "Comedy",
                            Description = "No fact checks",
                            ISBN = "978-3-16-148410-0",
                            Price = 299.89999999999998,
                            Publisher = "StackOverflow",
                            Title = "Why HTML is a programming language",
                            TotalPages = 180
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
